

t1 = str(input("Digite a tarefa: "))
t2 = str(input("Digite a tarefa: "))
t3 = str(input("Digite a tarefa: "))
t4 = str(input("Digite a tarefa: "))
t5 = str(input("Digite a tarefa: "))
t6 = str(input("Digite a tarefa: "))
t7 = str(input("Digite a tarefa: "))
t8 = str(input("Digite a tarefa: "))
t9 = str(input("Digite a tarefa: "))
t10 = str(input("Digite a tarefa: "))

print(f"Tarefa 1: {t1}")
print(f"Tarefa 2: {t2}")
print(f"Tarefa 3: {t3}")
print(f"Tarefa 4: {t4}")
print(f"Tarefa 5: {t5}")
print(f'tarefa 6: {t6}')
print(f'tarefa 7: {t7}')
print(f'tarefa 8: {t8}')
print(f'tarefa 9: {t9}')
print(f'tarefa 10: {t10}')